### ISSUE TITLE
Refactor the `How to get involved?` links

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/.github#3]
## Description

We recently migrated most of the content present on the `About_moja_global` repository to our [Community Website](https://community.moja.global). We would like to refer to the published documentation on the community website, rather than the `About_moja_global`. 

In the `How to get involved?` section, we refer to some quick links that refer to the `About_moja_global`. We would like those links to be refactored and refer to the community website links rather than the `About_moja_global` repository.

https://community.moja.global/community/contributing
https://community.moja.global/community/code-contribution
https://community.moja.global/community/docs-contribution
https://community.moja.global/community/management-contribution

**Comment by caseynv** [comment]
Hi, I am an outreachy applicant. I'd like to work on this.

**Comment by caseynv** [comment]
could not get the .js file to refactor the links. what is the .js for it?

**Comment by caseynv** [comment]
Done

**Comment by HarshCasper** [comment]
Hi @caseynv 

I don't see your PR yet. Can you please make the fix? Thanks.

**Comment by caseynv** [comment]
Hi @harshcasper,
I worked on 2 issues(#135 and #3) and made a pr for both already.

**Comment by HarshCasper** [comment]
Hi @caseynv 

I guess there has been a misunderstanding. We would like the PR to be on this repo (`moja-global/.github`) as well. Appreciate your contribution on the community website, but the issue concerned this repo.

**Comment by caseynv** [comment]
Hi I push the added the website folder I worked on and tried to push to my remote repo but I encountered errors. Please could you walk me through what and how I should do to push the changes to the .github repo to create a pr
