### ISSUE TITLE
Create a new section `Get involved`

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/.github#4]
## Description

Create a new section `Get involved` to provide a high-level overview of the fact that moja global accepts contributions from a wide variety of contributors.

This section can be ideally added after `What we do?` section and should be followed by `Contributing to the ecosystem.

Here is some boilerplate content picked up from the moja global flyer that can be utilized for our purpose:

> Moja global thrives on the energy and spirit of our community. We are lucky to have an engaged team of scientists, geospatial analysts, policymakers, technical writers, software and web developers contributing to our ambition of supporting equitable and evidence-based policy of land and ecosystem management.

> Our goal is to make software for land-use planning, climate change mitigation and policy analysis. Our tools are available to all potential users, including governments, commercial entities, financial institutions, and intergovernmental bodies.

> The participation and growth of our community are generously supported by mentorship programs such as Google Season of Code, Google Season of Documentation, Outreachy and the Linux Foundation Experience (LFX).

Appropriate changes can be made to the same before sending out a PR.

**Comment by caseynv** [comment]
Hi, I am an outreachy applicant. I'd like to work on this.

**Comment by HarshCasper** [comment]
> Hi, I am an outreachy applicant. I'd like to work on this.

Please work on the issue already assigned to you.

**Comment by RaOneG** [comment]
Hello @HarshCasper, I am Rawan an Outreachy applicant. I would like to work on this issue.

**Comment by Ashara-kosi** [comment]
Hello @HarshCasper, I am an Outreachy applicant and would like to work on this issue.

**Comment by asmijafar20** [comment]
Hey, I would like to work on this issue. Please assign it to me.
